#!/bin/bash
# Audio Configuration Scripts Usage Guide

echo "======================================================================="
echo "  PCM5102A Audio Configuration Scripts"
echo "  Luckfox Lyra Zero W"
echo "======================================================================="
echo ""
echo "All scripts accept an optional SSH target as first argument."
echo "Default: lyra@192.168.123.100"
echo ""
echo "USAGE EXAMPLES:"
echo "-----------------------------------------------------------------------"
echo ""
echo "1. Setup Audio System (User + ALSA Config)"
echo "   ./setup-audio-system.sh                   # Use default target"
echo "   ./setup-audio-system.sh user@10.0.0.50    # Custom target"
echo ""
echo "   What it does:"
echo "   - Adds user to audio group"
echo "   - Deploys /etc/asound.conf"
echo "   - Verifies basic configuration"
echo ""
echo "-----------------------------------------------------------------------"
echo ""
echo "2. Verify Audio Configuration"
echo "   ./verify-audio-remote.sh                  # Use default target"
echo "   ./verify-audio-remote.sh user@10.0.0.50   # Custom target"
echo ""
echo "   What it checks:"
echo "   - Sound card registration"
echo "   - Device tree properties (all 6 required properties)"
echo "   - Pin configuration (MCLK, SCLK, LRCK, SDO0)"
echo "   - TDM configuration (32 slots × 64 bits)"
echo "   - User permissions (audio group)"
echo "   - ALSA configuration"
echo "   - Audio device access (tests if speaker-test hangs)"
echo "   - Quick playback test"
echo ""
echo "-----------------------------------------------------------------------"
echo ""
echo "3. Complete Demo (Setup + Verify + Test)"
echo "   ./demo-audio-setup.sh                     # Interactive demo"
echo ""
echo "   What it does:"
echo "   - Runs setup script"
echo "   - Waits for user to logout/login"
echo "   - Runs verification"
echo "   - Plays test tone if successful"
echo ""
echo "-----------------------------------------------------------------------"
echo ""
echo "4. Other Scripts (Run ON the board)"
echo "   verify-audio-config.sh    # Detailed diagnostics (run on board)"
echo "   test-audio.sh             # Play test tones (run on board)"
echo "   build-overlays.sh         # Compile device tree overlays"
echo "   load-overlay.sh           # Load overlay at runtime"
echo ""
echo "======================================================================="
echo ""
echo "WORKFLOW:"
echo "-----------------------------------------------------------------------"
echo ""
echo "After flashing new image with corrected device tree:"
echo ""
echo "  1. ./setup-audio-system.sh lyra@192.168.123.100"
echo "  2. Reboot board or logout/login on board"
echo "  3. ./verify-audio-remote.sh lyra@192.168.123.100"
echo "  4. ssh lyra@192.168.123.100 'speaker-test -D hw:0,0 -t sine'"
echo ""
echo "If verification shows missing device tree properties:"
echo "  → Check DIAGNOSIS.md for detailed analysis"
echo "  → Rebuild image with correct DTS"
echo "  → Flash and try again"
echo ""
echo "======================================================================="
echo ""
